import math

from graph_model import (
    DEFAULT_EDGE_COLOR,
    DEFAULT_EDGE_LABEL_COLOR,
    DEFAULT_EDGE_LABEL_SIZE,
    DEFAULT_NODE_COLOR,
    DEFAULT_NODE_LABEL_COLOR,
    DEFAULT_NODE_LABEL_POSITION,
    DEFAULT_NODE_LABEL_SIZE,
    DEFAULT_NODE_OUTLINE_COLOR,
    DEFAULT_PENCIL_COLOR,
    DEFAULT_PENCIL_WIDTH,
    DEFAULT_TEXT_COLOR,
    DEFAULT_TEXT_SIZE,
)


TIKZ_EDGE_STYLES = {
    "solid": "",
    "dashed": "dashed, ",
    "dotted": "dotted, ",
    "dashdot": "dash pattern=on 6pt off 3pt on 1.5pt off 3pt, ",
}


class MatrixBuilder:
    @staticmethod
    def build(nodes, edges):
        n = len(nodes)
        m = len(edges)
        adjacency = [[0] * n for _ in range(n)]
        incidence = [[0] * m for _ in range(n)]
        id_index = {node.id: idx for idx, node in enumerate(nodes)}

        for idx, edge in enumerate(edges):
            if edge.source in id_index and edge.target in id_index:
                u = id_index[edge.source]
                v = id_index[edge.target]
                adjacency[u][v] += 1
                if u == v:
                    incidence[u][idx] = 0 if edge.directed else 2
                    continue

                incidence[u][idx] = 1
                if edge.directed:
                    incidence[v][idx] = -1
                else:
                    adjacency[v][u] += 1
                    incidence[v][idx] = 1

        return adjacency, incidence

    @staticmethod
    def format(matrix):
        rows = ["\t".join(str(value) for value in row) for row in matrix]
        return "\n".join(rows)


class TikzExporter:
    def __init__(
        self,
        nodes,
        edges,
        regions,
        texts,
        background,
        canvas_width,
        canvas_height,
        pencil_strokes=None,
        show_node_labels=False,
        show_edge_labels=False,
        show_labels=None,
    ):
        self.nodes = nodes
        self.edges = edges
        self.regions = regions
        self.texts = texts
        self.background = background
        self.canvas_width = canvas_width
        self.canvas_height = canvas_height
        self.pencil_strokes = pencil_strokes or []
        if show_labels is not None:
            show_node_labels = show_labels
            show_edge_labels = show_labels
        self.show_node_labels = show_node_labels
        self.show_edge_labels = show_edge_labels

    def generate(self):
        lines = [
            "% TikZ export generated by Graph Drawer",
            "\\begin{tikzpicture}[x=1cm, y=1cm]",
        ]
        lines.extend(self._background_lines())
        lines.extend(self._region_lines())
        lines.extend(self._pencil_lines())
        lines.extend(self._edge_lines())
        lines.extend(self._node_lines())
        lines.extend(self._text_lines())
        lines.append("\\end{tikzpicture}")
        return "\n".join(lines)

    def _background_lines(self):
        if self.background.mode == "grid":
            return self._grid_lines()
        if self.background.mode == "axes":
            return self._axis_lines()
        return []

    def _grid_lines(self):
        xmin, xmax, ymin, ymax = self._canvas_bounds()
        return [
            (
                "\\draw[step=1, help lines, color=gray!25] "
                f"({self._fmt(xmin)},{self._fmt(ymin)}) grid ({self._fmt(xmax)},{self._fmt(ymax)});"
            )
        ]

    def _axis_lines(self):
        xmin, xmax, ymin, ymax = self._canvas_bounds()
        lines = []

        if ymin <= 0 <= ymax:
            lines.append(
                f"\\draw[->, color=gray!65] ({self._fmt(xmin)},0) -- ({self._fmt(xmax)},0) node[right] {{$x$}};"
            )

        if xmin <= 0 <= xmax:
            lines.append(
                f"\\draw[->, color=gray!65] (0,{self._fmt(ymin)}) -- (0,{self._fmt(ymax)}) node[above] {{$y$}};"
            )

        if xmin <= 0 <= xmax and ymin <= 0 <= ymax:
            lines.append("\\node[below left, color=gray!65, font=\\scriptsize] at (0,0) {$O$};")

        if ymin <= 0 <= ymax:
            for tick in self._tick_values(xmin, xmax):
                if tick == 0:
                    continue
                lines.append(
                    f"\\draw[color=gray!55] ({tick},0.06) -- ({tick},-0.06) "
                    f"node[below, font=\\scriptsize] {{{tick}}};"
                )

        if xmin <= 0 <= xmax:
            for tick in self._tick_values(ymin, ymax):
                if tick == 0:
                    continue
                lines.append(
                    f"\\draw[color=gray!55] (0.06,{tick}) -- (-0.06,{tick}) "
                    f"node[left, font=\\scriptsize] {{{tick}}};"
                )

        return lines

    def _region_lines(self):
        lines = []
        for region in self.regions:
            if len(region.points) < 6:
                continue

            points = [
                self._point(region.points[i], region.points[i + 1])
                for i in range(0, len(region.points), 2)
            ]
            color = self._tikz_rgb(region.color)
            lines.append(
                f"\\filldraw[draw={color}, fill={color}, fill opacity={region.alpha}] "
                f"{' -- '.join(points)} -- cycle;"
            )

            if region.label:
                xs = region.points[::2]
                ys = region.points[1::2]
                cx = sum(xs) / len(xs)
                cy = sum(ys) / len(ys)
                lines.append(
                    f"\\node[font=\\small] at {self._point(cx, cy)} {{{self._latex_escape(region.label)}}};"
                )

        return lines

    def _pencil_lines(self):
        lines = []
        for stroke in self.pencil_strokes:
            if len(stroke.points) < 4:
                continue
            points = [
                self._point(stroke.points[i], stroke.points[i + 1])
                for i in range(0, len(stroke.points) - 1, 2)
            ]
            color = self._tikz_rgb(getattr(stroke, "color", DEFAULT_PENCIL_COLOR))
            width = self._fmt(max(0.2, float(getattr(stroke, "width", DEFAULT_PENCIL_WIDTH)) * 0.35))
            lines.append(
                f"\\draw[draw={color}, line width={width}pt, rounded corners=0.8pt] "
                f"{' -- '.join(points)};"
            )
        return lines

    def _edge_lines(self):
        lines = []
        for index, edge in enumerate(self.edges):
            color = self._tikz_rgb(edge.color or DEFAULT_EDGE_COLOR)
            arrow = "->, " if edge.directed else ""
            style = TIKZ_EDGE_STYLES.get(edge.style, "")
            line_width = self._fmt(max(0.2, float(edge.width) * 0.35))
            label = ""
            label_text = edge.label or (self._edge_auto_label(index) if self.show_edge_labels else "")
            if label_text:
                label_color = self._tikz_rgb(getattr(edge, "label_color", DEFAULT_EDGE_LABEL_COLOR))
                label_size = max(6, int(getattr(edge, "label_size", DEFAULT_EDGE_LABEL_SIZE)))
                label = (
                    f" node[midway, inner sep=1.5pt, text={label_color}, "
                    f"font=\\fontsize{{{label_size}}}{{{label_size + 2}}}\\selectfont\\itshape] "
                    f"{{{self._latex_escape(label_text)}}}"
                )
            path_options = self._tikz_edge_path_options(edge)
            if edge.source == edge.target:
                loop_options = ", ".join([option for option in [arrow.strip(", "), style.strip(", "), "draw=" + color, f"line width={line_width}pt", path_options] if option])
                lines.append(f"\\path[{loop_options}] (v{edge.source}) edge{label} (v{edge.target});")
                continue
            lines.append(
                f"\\draw[{arrow}{style}draw={color}, line width={line_width}pt] "
                f"(v{edge.source}) to[{path_options}]{label} (v{edge.target});"
            )
        return lines

    def _tikz_edge_path_options(self, edge):
        if edge.source == edge.target:
            index = self._edge_variant_index(edge)
            manual_offset = getattr(edge, "curve_offset", None) or 0
            looseness = self._fmt(max(3, 8 + index * 1.5 + manual_offset * 0.03))
            return f"loop above, looseness={looseness}"

        manual_offset = getattr(edge, "curve_offset", None)
        if manual_offset is not None:
            if abs(manual_offset) < 0.01:
                return ""
            angle = max(8, min(65, abs(manual_offset) * 0.75))
            return f"bend left={self._fmt(angle)}" if manual_offset > 0 else f"bend right={self._fmt(angle)}"

        members = self._edge_group_members(edge)
        if len(members) <= 1:
            return ""
        index = members.index(edge)
        offset = index - (len(members) - 1) / 2
        angle = max(12, min(55, abs(offset) * 22))
        return f"bend left={self._fmt(angle)}" if offset > 0 else f"bend right={self._fmt(angle)}"

    def _edge_variant_index(self, edge):
        members = self._edge_group_members(edge)
        return members.index(edge) if edge in members else 0

    def _edge_group_members(self, edge):
        key = self._edge_group_key(edge)
        return [candidate for candidate in self.edges if self._edge_group_key(candidate) == key]

    def _edge_group_key(self, edge):
        if edge.source == edge.target:
            return ("loop", edge.source)
        return ("pair", min(edge.source, edge.target), max(edge.source, edge.target))

    def _node_lines(self):
        lines = []
        for index, node in enumerate(self.nodes):
            fill_color = self._tikz_rgb(node.color or DEFAULT_NODE_COLOR)
            outline_color = self._tikz_rgb(getattr(node, "outline_color", DEFAULT_NODE_OUTLINE_COLOR))
            label_size = max(6, int(getattr(node, "label_size", DEFAULT_NODE_LABEL_SIZE)))
            label = self._latex_escape(node.label or (str(index + 1) if self.show_node_labels else ""))
            size = self._fmt(max(0.15, node.radius / self.background.normalized_scale() * 2))
            label_position = getattr(node, "label_position", DEFAULT_NODE_LABEL_POSITION)
            raw_label_color = getattr(node, "label_color", DEFAULT_NODE_LABEL_COLOR)
            label_color = self._tikz_rgb(self._effective_node_label_color(raw_label_color, label_position == "beside"))
            node_text = "" if label_position == "beside" and label else label
            lines.append(
                f"\\node[circle, draw={outline_color}, fill={fill_color}, text={label_color}, minimum size={size}cm, "
                f"inner sep=1pt, font=\\fontsize{{{label_size}}}{{{label_size + 2}}}\\selectfont] "
                f"(v{node.id}) at {self._point(node.x, node.y)} {{{node_text}}};"
            )
            if label and label_position == "beside":
                label_x, label_y = self._node_label_anchor(node)
                lines.append(
                    f"\\node[anchor=west, inner sep=1pt, "
                    f"text={label_color}, font=\\fontsize{{{label_size}}}{{{label_size + 2}}}\\selectfont\\bfseries] "
                    f"at {self._point(label_x, label_y)} {{{label}}};"
                )
        return lines

    def _node_label_anchor(self, node):
        radius = getattr(node, "radius", 14)
        return node.x + radius + 8, node.y - radius - 8

    def _effective_node_label_color(self, color, side_label=False):
        if side_label and isinstance(color, str) and color.lower() == "#ffffff":
            return "#1f2937"
        return color

    def _edge_auto_label(self, index):
        label = ""
        value = index
        while True:
            label = chr(ord("a") + value % 26) + label
            value = value // 26 - 1
            if value < 0:
                return label

    def _text_lines(self):
        lines = []
        for text in self.texts:
            color = self._tikz_rgb(text.color or DEFAULT_TEXT_COLOR)
            content = self._latex_escape(text.text)
            font_size = max(6, int(getattr(text, "font_size", DEFAULT_TEXT_SIZE)))
            line_height = font_size + 2
            text_width = self._fmt(max(0.5, text.width / self.background.normalized_scale()))
            lines.append(
                f"\\node[anchor=north west, text={color}, text width={text_width}cm, "
                f"font=\\fontsize{{{font_size}}}{{{line_height}}}\\selectfont] "
                f"at {self._point(text.x, text.y)} {{{content}}};"
            )
        return lines

    def _canvas_bounds(self):
        x0, y_top = self.background.canvas_to_units(0, 0)
        x1, y_bottom = self.background.canvas_to_units(self.canvas_width, self.canvas_height)
        return min(x0, x1), max(x0, x1), min(y_top, y_bottom), max(y_top, y_bottom)

    def _point(self, x, y):
        ux, uy = self.background.canvas_to_units(x, y)
        return f"({self._fmt(ux)},{self._fmt(uy)})"

    def _tick_values(self, start, end):
        first = math.ceil(start)
        last = math.floor(end)
        count = max(0, last - first + 1)
        if count == 0:
            return []

        stride = max(1, math.ceil(count / 80))
        return list(range(first, last + 1, stride))

    def _tikz_rgb(self, hex_color):
        if not isinstance(hex_color, str) or len(hex_color) != 7 or not hex_color.startswith("#"):
            hex_color = DEFAULT_EDGE_COLOR
        try:
            r = int(hex_color[1:3], 16)
            g = int(hex_color[3:5], 16)
            b = int(hex_color[5:7], 16)
        except ValueError:
            r, g, b = 51, 51, 51
        return f"{{rgb,255:red,{r};green,{g};blue,{b}}}"

    def _fmt(self, value):
        text = f"{value:.2f}".rstrip("0").rstrip(".")
        return text if text and text != "-0" else "0"

    def _latex_escape(self, value):
        replacements = {
            "\\": r"\textbackslash{}",
            "&": r"\&",
            "%": r"\%",
            "$": r"\$",
            "#": r"\#",
            "_": r"\_",
            "{": r"\{",
            "}": r"\}",
            "~": r"\textasciitilde{}",
            "^": r"\textasciicircum{}",
        }
        return "".join(replacements.get(char, char) for char in str(value))
